Цель работы: необходимо реализовать базовый анализ датасета: вывести весь датасет и описать его, вывести размерноть массива, вывести наименование всех колонок, написать что они означают в датасете, вывести все уникальные значения,отсортировать по определенным параметрам, удалить ненужные столбцы или строчки, заменить определенные значения в датасете , удалить дубликаты, провести анализ с помощью функций info, провести анализ с помощью функций describe, провести выборку данных по строкам и столбцам с помощью loc, сохранить новый датасет, сделать вывод по каждому пункту и описать все.

In [1]:
import pandas as pd
import numpy as np
waterQuality1 = pd.read_csv("waterQuality1.csv") 
waterQuality1

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,...,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,...,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,0.05,7.78,0.00,1.95,0.040,0.10,0.03,0.03,1.37,0.00,...,0.197,14.29,1.00,0.005,3.57,2.13,0.09,0.06,0.03,1
7995,0.05,24.22,0.02,0.59,0.010,0.45,0.02,0.02,1.48,0.00,...,0.031,10.27,1.00,0.001,1.48,1.11,0.09,0.10,0.08,1
7996,0.09,6.85,0.00,0.61,0.030,0.05,0.05,0.02,0.91,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1
7997,0.01,10,0.01,2.00,0.000,2.00,0.00,0.09,0.00,0.00,...,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,1
7998,0.04,6.85,0.01,0.70,0.030,0.05,0.01,0.03,1.00,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1

1. Выводим весь датасет. В данном датасете (количество компонентов в воде) находятся следующие данные: алюминий, аммиак, мышьяк, барий, кадмий, хлорамин, бактерии, фторид, хром, медь, нитраты, свинец, нитриты , перхлорат, ртуть, радий, селен, серебро, уран, безопасность (количсетво данных веществ в воде).

In [28]:
waterQuality1.shape

(7999, 21)

2. Выводим размерность массива

In [5]:
waterQuality1.columns

Index(['aluminium', 'ammonia', 'arsenic', 'barium', 'cadmium', 'chloramine',
       'chromium', 'copper', 'flouride', 'bacteria', 'viruses', 'lead',
       'nitrates', 'nitrites', 'mercury', 'perchlorate', 'radium', 'selenium',
       'silver', 'uranium', 'is_safe'],
      dtype='object')

3. Выводим наименование всех колонок и то, что они значат: алюминий, аммиак, мышьяк, барий, кадмий, хлорамин, бактерии, фторид, хром, медь, нитраты, свинец, нитриты , перхлорат, ртуть, радий, селен, серебро, уран, безопасность.

In [6]:
waterQuality1["aluminium"].unique()

array([1.65, 2.32, 1.01, 1.36, 0.92, 0.94, 2.36, 3.93, 0.6 , 0.22, 3.27,
       1.35, 1.88, 4.93, 2.89, 0.61, 3.47, 2.11, 4.88, 4.12, 0.68, 1.15,
       0.27, 4.32, 3.31, 1.82, 3.42, 4.41, 4.57, 1.69, 1.87, 2.71, 1.63,
       0.01, 4.49, 3.52, 4.35, 2.51, 2.34, 1.71, 3.45, 3.37, 3.13, 0.29,
       1.51, 1.09, 2.68, 0.3 , 0.23, 2.55, 0.86, 0.24, 3.63, 3.26, 0.42,
       0.77, 0.58, 3.82, 2.78, 3.62, 3.88, 4.64, 2.25, 0.54, 4.62, 2.5 ,
       3.08, 3.03, 2.85, 1.38, 2.73, 3.02, 1.96, 2.35, 2.45, 2.67, 1.12,
       3.3 , 0.43, 1.19, 0.85, 0.5 , 4.75, 1.89, 3.75, 3.32, 1.75, 2.66,
       2.76, 2.63, 0.04, 0.88, 2.22, 4.91, 4.8 , 0.47, 1.62, 0.09, 4.66,
       2.74, 1.79, 4.15, 3.78, 2.91, 4.3 , 3.24, 3.53, 3.04, 2.21, 2.47,
       1.92, 1.22, 2.12, 4.19, 4.21, 4.07, 2.56, 3.55, 3.94, 0.8 , 2.59,
       3.9 , 3.15, 0.18, 3.86, 1.25, 2.29, 0.07, 4.18, 4.34, 2.39, 0.9 ,
       0.89, 2.4 , 3.69, 4.71, 3.36, 4.46, 4.5 , 0.57, 2.69, 2.17, 1.32,
       5.  , 2.6 , 0.35, 3.83, 2.9 , 1.56, 2.23, 3.81, 2.75, 0.81, 4.  ,
       4.08, 1.55, 2.42, 2.99, 1.43, 1.66, 3.38, 4.42, 3.43, 3.65, 4.86,
       2.82, 1.05, 0.73, 1.21, 2.15, 3.6 , 1.73, 3.35, 0.37, 0.79, 0.99,
       1.86, 4.84, 3.09, 1.72, 3.29, 0.11, 4.04, 3.71, 3.79, 3.05, 0.84,
       1.98, 0.59, 0.36, 1.4 , 1.46, 2.02, 0.  , 0.93, 0.78, 4.48, 0.71,
       0.06, 0.87, 1.44, 4.36, 2.83, 2.58, 2.14, 0.15, 2.01, 2.18, 4.38,
       3.73, 2.97, 3.85, 3.95, 2.06, 3.84, 3.97, 4.44, 2.96, 3.44, 2.2 ,
       1.14, 2.37, 0.13, 3.89, 2.09, 4.79, 2.54, 0.19, 4.77, 0.76, 4.27,
       1.9 , 4.26, 3.19, 1.24, 1.67, 2.94, 0.49, 4.1 , 4.68, 2.26, 1.2 ,
       3.12, 3.67, 3.59, 3.46, 4.81, 2.79, 3.49, 1.77, 2.7 , 4.53, 0.39,
       1.07, 0.62, 3.96, 0.14, 0.83, 0.72, 3.98, 4.39, 4.56, 3.06, 2.92,
       0.95, 2.24, 3.18, 2.61, 2.33, 1.93, 4.52, 3.91, 4.58, 1.81, 3.01,
       2.16, 3.39, 3.51, 1.08, 1.99, 1.53, 4.73, 2.13, 1.34, 3.68, 2.04,
       1.45, 2.8 , 3.34, 2.52, 2.46, 3.92, 4.69, 0.63, 3.  , 4.31, 2.64,
       0.65, 2.65, 4.29, 2.62, 4.13, 0.45, 0.33, 3.25, 3.72, 1.54, 4.76,
       0.7 , 1.5 , 1.91, 0.05, 4.96, 4.7 , 3.57, 4.05, 4.98, 4.55, 2.77,
       1.52, 4.95, 2.08, 1.37, 1.49, 4.11, 2.1 , 4.85, 0.48, 2.88, 0.17,
       2.05, 0.41, 0.97, 4.25, 4.23, 2.28, 0.96, 4.6 , 4.65, 0.46, 4.03,
       1.06, 0.82, 4.06, 1.39, 1.03, 4.87, 1.48, 3.61, 3.74, 4.82, 0.75,
       2.38, 0.25, 0.53, 3.07, 3.99, 1.83, 0.21, 1.94, 0.55, 2.72, 2.48,
       1.61, 4.33, 0.32, 4.72, 0.31, 1.76, 4.74, 4.61, 1.28, 3.48, 0.34,
       2.41, 3.14, 3.54, 0.56, 3.76, 3.11, 0.69, 1.97, 4.59, 1.74, 0.26,
       0.16, 3.2 , 1.27, 3.5 , 0.38, 4.78, 3.21, 1.16, 1.1 , 2.27, 4.94,
       4.2 , 2.03, 1.95, 4.67, 2.93, 4.83, 0.12, 1.41, 1.68, 1.7 , 2.98,
       4.24, 1.18, 0.03, 0.67, 1.57, 0.02, 0.52, 0.91, 3.64, 4.4 , 0.44,
       3.56, 2.53, 1.85, 3.28, 3.77, 0.4 , 4.9 , 3.87, 0.74, 1.13, 0.28,
       4.45, 4.51, 3.41, 2.84, 0.66, 4.17, 4.37, 4.54, 2.3 , 1.17, 3.8 ,
       1.8 , 2.81, 1.84, 3.58, 1.3 , 2.44, 5.05, 2.95, 1.6 , 4.47, 3.7 ,
       2.87, 1.26, 1.78, 3.4 , 1.04, 4.89, 4.09, 3.1 , 0.64, 2.07, 0.98,
       2.19, 0.2 , 4.43, 4.02, 1.29, 2.31, 3.17, 4.01, 1.  , 3.23, 4.63,
       1.58, 2.57, 1.59, 0.1 , 5.01, 5.03, 1.42, 4.16, 1.02, 4.28, 0.51,
       1.11, 4.92, 3.66, 2.43, 1.33, 3.16, 4.99, 2.  , 1.23, 0.08, 3.33])

In [8]:
waterQuality1["ammonia"].unique()

array(['9.08', '21.16', '14.02', ..., '2.78', '27.12', '10'], dtype=object)

In [9]:
waterQuality1["arsenic"].unique()

array([4.00e-02, 1.00e-02, 3.00e-02, 2.00e-02, 1.00e-03, 5.00e-02,
       3.10e-01, 3.50e-01, 4.80e-01, 8.70e-01, 1.70e-01, 2.10e-01,
       8.10e-01, 8.80e-01, 6.60e-01, 7.00e-01, 5.40e-01, 4.00e-01,
       5.70e-01, 3.70e-01, 1.00e-01, 9.90e-01, 2.50e-01, 7.70e-01,
       2.90e-01, 4.90e-01, 5.90e-01, 6.50e-01, 6.80e-01, 3.00e-01,
       9.30e-01, 8.40e-01, 1.60e-01, 4.60e-01, 1.50e-01, 2.20e-01,
       7.10e-01, 7.90e-01, 8.00e-02, 5.30e-01, 3.60e-01, 5.20e-01,
       6.00e-02, 9.20e-01, 5.60e-01, 4.40e-01, 3.90e-01, 6.70e-01,
       8.60e-01, 7.50e-01, 9.60e-01, 8.00e-01, 8.90e-01, 7.40e-01,
       4.70e-01, 4.30e-01, 5.10e-01, 1.20e-01, 7.80e-01, 6.30e-01,
       7.60e-01, 3.30e-01, 1.80e-01, 9.10e-01, 9.50e-01, 6.10e-01,
       7.30e-01, 2.70e-01, 1.03e+00, 1.01e+00, 9.00e-02, 2.80e-01,
       6.00e-01, 1.04e+00, 9.80e-01, 5.80e-01, 7.00e-02, 6.20e-01,
       8.50e-01, 3.80e-01, 4.10e-01, 9.70e-01, 2.60e-01, 3.40e-01,
       1.00e+00, 2.00e-01, 1.10e-01, 8.30e-01, 4.20e-01, 1.40e-01,
       1.05e+00, 4.50e-01, 6.40e-01, 9.40e-01, 2.40e-01, 1.30e-01,
       6.90e-01, 5.00e-01, 2.30e-01, 9.00e-01, 1.90e-01, 1.02e+00,
       8.20e-01, 3.20e-01, 7.20e-01, 5.50e-01, 0.00e+00])

In [10]:
waterQuality1["barium"].unique()

array([2.85, 3.31, 0.58, 2.96, 0.2 , 2.88, 1.35, 0.66, 0.71, 1.37, 2.69,
       0.84, 2.78, 3.05, 3.77, 0.59, 0.06, 0.88, 0.36, 3.43, 0.04, 0.97,
       0.55, 2.6 , 0.68, 0.46, 0.85, 2.8 , 1.76, 3.04, 2.01, 3.74, 3.02,
       2.54, 2.93, 1.87, 1.58, 2.67, 3.63, 1.86, 0.25, 0.52, 2.16, 3.94,
       3.98, 2.5 , 3.5 , 1.31, 1.98, 1.07, 2.79, 3.86, 0.65, 3.45, 3.53,
       1.71, 0.22, 2.27, 3.11, 0.57, 2.24, 3.92, 1.67, 1.47, 1.78, 3.76,
       2.86, 3.25, 0.07, 3.08, 1.28, 0.75, 0.17, 2.97, 2.99, 3.18, 1.38,
       1.36, 3.54, 2.09, 2.  , 3.28, 1.74, 2.44, 0.92, 0.13, 2.73, 3.2 ,
       0.29, 1.46, 1.32, 3.61, 0.16, 3.84, 2.36, 1.5 , 2.46, 1.99, 0.76,
       2.66, 2.9 , 1.6 , 2.34, 1.4 , 1.01, 1.11, 3.65, 1.65, 3.29, 1.94,
       3.16, 1.8 , 2.63, 0.86, 3.64, 0.87, 3.15, 1.03, 1.82, 1.39, 1.14,
       3.58, 3.35, 3.57, 1.81, 1.63, 0.56, 3.93, 1.72, 0.28, 3.09, 1.93,
       0.12, 2.42, 3.33, 2.53, 2.57, 0.78, 1.84, 3.03, 3.51, 0.19, 3.34,
       2.91, 3.48, 0.33, 2.39, 2.07, 2.22, 1.18, 0.69, 0.82, 2.76, 2.15,
       2.13, 2.56, 1.05, 1.92, 0.7 , 0.48, 3.06, 0.62, 2.64, 1.88, 1.19,
       1.13, 1.62, 0.89, 1.89, 3.69, 0.47, 2.28, 3.14, 1.41, 3.52, 3.83,
       2.74, 2.17, 1.91, 3.73, 1.53, 1.33, 0.74, 2.47, 0.23, 1.22, 1.95,
       0.96, 0.01, 0.73, 2.38, 3.89, 2.3 , 3.01, 0.51, 0.37, 2.19, 0.39,
       3.81, 0.77, 3.38, 2.83, 3.07, 3.68, 1.68, 1.79, 3.67, 1.69, 3.4 ,
       1.12, 3.8 , 2.89, 3.79, 1.08, 0.26, 3.95, 1.97, 0.81, 0.8 , 3.85,
       2.65, 0.43, 0.53, 3.  , 3.88, 3.39, 2.45, 0.9 , 2.2 , 1.64, 3.21,
       1.25, 3.49, 0.38, 2.84, 2.75, 3.75, 0.79, 2.4 , 1.17, 2.72, 3.55,
       0.14, 0.6 , 1.75, 0.31, 2.35, 3.22, 3.72, 0.64, 1.21, 1.77, 0.02,
       3.37, 2.62, 2.31, 2.04, 1.52, 2.06, 2.52, 3.27, 1.09, 3.47, 1.02,
       2.26, 0.42, 0.54, 3.91, 1.85, 0.41, 3.32, 2.49, 1.34, 3.62, 0.35,
       2.55, 3.82, 0.72, 1.1 , 2.58, 3.19, 2.7 , 4.  , 1.43, 3.44, 1.29,
       1.45, 1.56, 0.91, 0.67, 1.04, 1.42, 3.96, 3.9 , 2.51, 2.68, 3.36,
       2.61, 3.59, 0.34, 2.43, 0.27, 1.96, 0.63, 0.49, 1.54, 0.94, 2.11,
       1.26, 3.17, 2.29, 3.99, 1.51, 3.1 , 2.94, 0.24, 1.57, 3.3 , 0.15,
       0.93, 2.03, 2.87, 0.18, 0.45, 1.59, 3.6 , 3.41, 1.24, 3.46, 2.1 ,
       3.56, 1.9 , 1.48, 0.83, 2.25, 3.71, 3.87, 2.48, 2.95, 0.11, 0.03,
       3.78, 1.83, 0.09, 1.06, 2.71, 2.37, 2.77, 1.66, 3.26, 1.16, 0.1 ,
       1.  , 0.61, 2.82, 2.59, 3.42, 3.7 , 2.14, 0.3 , 0.32, 3.23, 0.98,
       2.33, 3.66, 4.32, 1.27, 0.95, 4.66, 4.45, 1.23, 4.9 , 4.09, 4.35,
       2.98, 1.73, 4.03, 4.18, 4.14, 4.25, 4.11, 1.7 , 3.13, 3.97, 4.4 ,
       1.61, 2.32, 4.34, 4.38, 4.17, 4.05, 3.24, 4.29, 1.3 , 4.16, 4.02,
       4.47, 1.2 , 4.21, 4.39, 2.41, 0.99, 4.22, 4.44, 4.26, 4.69, 4.42,
       4.5 , 4.56, 4.36, 2.81, 4.37, 4.46, 4.72, 4.64, 1.49, 2.23, 4.01,
       2.12, 1.15, 2.08, 4.27, 1.55, 4.48, 4.06, 2.18, 4.28, 4.04, 4.77,
       4.52, 4.54, 4.43, 4.1 , 2.02, 3.12, 0.5 , 4.07, 4.65, 4.57, 4.41,
       4.83, 4.82, 4.12, 2.21, 4.49, 4.67, 4.59, 4.75, 2.92, 4.33, 1.44,
       4.6 , 4.88, 4.19, 4.31, 4.68, 4.89, 4.15, 4.13, 4.24, 4.53, 4.81,
       0.21, 4.23, 4.2 , 4.74, 4.51, 0.44, 4.84, 4.08, 4.87, 4.61, 4.73,
       4.94, 2.05, 4.63, 0.4 , 0.05, 0.08, 0.  ])

In [11]:
waterQuality1["cadmium"].unique()

array([0.007, 0.002, 0.008, 0.001, 0.006, 0.003, 0.004, 0.005, 0.009,
       0.01 , 0.08 , 0.04 , 0.03 , 0.07 , 0.09 , 0.12 , 0.1  , 0.02 ,
       0.05 , 0.11 , 0.   , 0.06 , 0.13 ])

In [12]:
waterQuality1["chloramine"].unique()

array([0.35, 5.28, 4.24, 7.23, 2.67, 0.8 , 1.28, 6.22, 3.14, 6.4 , 5.75,
       0.1 , 0.05, 0.7 , 5.99, 1.94, 5.29, 7.78, 1.21, 0.01, 4.57, 3.47,
       3.74, 7.24, 4.07, 7.22, 2.55, 2.87, 6.63, 2.78, 5.87, 2.86, 4.  ,
       4.25, 7.75, 4.55, 4.94, 0.64, 4.3 , 2.24, 2.4 , 2.9 , 3.58, 2.99,
       5.71, 1.26, 5.38, 0.22, 6.11, 0.68, 7.7 , 5.47, 7.97, 6.19, 4.08,
       2.49, 0.9 , 4.5 , 0.88, 1.13, 3.85, 6.16, 7.06, 3.43, 4.4 , 4.89,
       6.57, 2.15, 2.38, 4.77, 7.81, 2.79, 1.78, 1.97, 3.4 , 4.41, 5.27,
       3.35, 2.69, 6.06, 7.56, 3.55, 0.13, 7.52, 3.57, 6.02, 1.12, 6.1 ,
       0.19, 1.85, 3.32, 1.89, 0.46, 4.8 , 4.59, 6.25, 4.54, 5.22, 1.86,
       7.37, 7.36, 3.07, 2.89, 6.75, 3.2 , 3.11, 1.33, 4.43, 6.6 , 0.63,
       5.07, 5.14, 0.4 , 4.13, 2.52, 3.71, 1.87, 7.09, 2.26, 0.41, 3.42,
       5.65, 5.72, 0.89, 1.57, 2.74, 0.79, 7.8 , 3.49, 3.83, 3.81, 1.69,
       6.21, 1.07, 0.5 , 3.95, 7.59, 0.98, 4.95, 2.45, 1.36, 6.5 , 4.68,
       5.1 , 3.61, 4.23, 0.81, 4.06, 4.42, 7.95, 6.45, 0.09, 3.26, 0.85,
       7.12, 3.69, 3.41, 3.1 , 1.53, 1.67, 2.13, 3.08, 7.91, 5.23, 0.07,
       6.2 , 5.48, 0.67, 3.91, 4.98, 0.97, 4.69, 1.49, 0.54, 2.8 , 7.47,
       2.91, 5.92, 6.8 , 1.81, 7.51, 0.92, 6.29, 5.54, 2.58, 5.83, 7.88,
       4.37, 5.17, 6.13, 6.9 , 4.36, 7.14, 5.25, 7.41, 1.44, 0.  , 7.33,
       1.02, 6.81, 4.62, 3.62, 6.69, 6.52, 0.83, 6.93, 4.73, 5.34, 2.84,
       3.45, 5.21, 2.1 , 1.83, 5.42, 7.02, 7.96, 7.07, 6.55, 6.76, 1.66,
       3.5 , 7.16, 6.04, 6.47, 6.99, 1.37, 7.17, 2.16, 6.68, 1.48, 1.09,
       0.57, 4.6 , 5.67, 4.01, 5.06, 0.75, 7.55, 0.76, 1.77, 1.63, 5.61,
       3.33, 1.98, 0.49, 1.6 , 6.56, 6.78, 3.04, 5.95, 4.38, 7.83, 7.43,
       0.71, 6.03, 5.58, 3.  , 3.25, 4.79, 3.48, 6.66, 6.84, 7.58, 2.63,
       2.2 , 2.11, 7.99, 4.78, 2.37, 5.68, 6.49, 4.22, 1.91, 6.37, 3.67,
       7.89, 5.4 , 2.21, 1.42, 4.84, 3.7 , 3.79, 6.89, 0.29, 7.18, 3.44,
       4.02, 6.12, 1.27, 7.65, 6.62, 2.5 , 5.98, 4.76, 6.98, 3.23, 4.93,
       3.03, 5.6 , 7.  , 6.59, 1.8 , 3.05, 2.17, 1.7 , 2.95, 0.73, 7.44,
       6.3 , 0.53, 4.52, 4.99, 5.66, 6.17, 1.54, 4.34, 3.31, 7.38, 4.86,
       7.82, 4.16, 4.87, 1.1 , 2.05, 5.81, 1.68, 1.75, 6.31, 7.93, 3.09,
       1.41, 3.01, 7.85, 3.15, 7.34, 5.3 , 4.33, 0.26, 7.25, 6.64, 4.49,
       1.19, 3.66, 3.65, 0.48, 4.91, 6.44, 5.56, 2.59, 1.64, 7.35, 0.45,
       4.81, 0.17, 4.18, 4.9 , 0.59, 6.42, 4.27, 6.95, 3.99, 2.83, 2.46,
       6.53, 7.57, 3.54, 1.39, 4.71, 6.48, 2.73, 0.06, 4.26, 2.03, 5.45,
       1.58, 6.24, 2.77, 3.93, 7.79, 1.43, 1.73, 6.27, 5.85, 6.71, 1.3 ,
       5.24, 5.89, 1.23, 3.29, 4.15, 5.57, 1.88, 7.3 , 2.94, 2.  , 4.11,
       3.51, 7.21, 6.26, 4.51, 1.74, 4.75, 0.12, 1.03, 1.22, 7.87, 0.25,
       4.1 , 1.04, 2.29, 4.74, 0.21, 0.6 , 5.59, 0.2 , 4.03, 0.66, 5.35,
       0.37, 2.14, 6.  , 1.84, 0.23, 3.96, 5.12, 0.78, 4.7 , 4.56, 3.75,
       7.49, 6.77, 0.93, 2.27, 0.3 , 6.85, 0.39, 4.96, 2.97, 4.85, 2.71,
       2.98, 2.34, 5.  , 0.08, 1.51, 3.78, 0.32, 3.17, 2.07, 3.21, 4.58,
       2.41, 5.73, 6.07, 3.36, 5.88, 2.01, 7.31, 3.88, 2.12, 6.86, 6.7 ,
       3.28, 2.51, 1.11, 5.9 , 1.4 , 5.33, 1.56, 3.3 , 3.37, 3.16, 1.16,
       7.48, 4.63, 7.86, 0.96, 0.34, 2.19, 2.35, 6.23, 7.08, 5.69, 4.39,
       7.54, 6.32, 6.83, 1.82, 3.64, 2.92, 6.92, 6.36, 3.53, 7.05, 1.9 ,
       3.82, 4.35, 6.28, 6.58, 3.98, 2.32, 7.15, 2.7 , 6.79, 1.62, 0.51,
       1.55, 7.92, 3.18, 5.76, 3.02, 6.14, 2.28, 4.05, 0.94, 1.65, 7.74,
       0.95, 1.45, 5.79, 5.11, 3.76, 6.97, 0.14, 6.09, 2.56, 6.35, 4.14,
       4.47, 6.43, 2.62, 7.72, 2.25, 5.64, 0.11, 3.84, 2.88, 0.65, 2.54,
       7.4 , 6.34, 1.35, 1.99, 2.57, 5.01, 1.96, 1.18, 3.52, 5.41, 2.81,
       7.66, 3.27, 0.38, 7.67, 4.97, 6.39, 1.79, 5.18, 2.47, 6.82, 7.42,
       2.96, 0.24, 5.04, 7.63, 5.09, 3.9 , 5.43, 6.15, 7.64, 1.01, 5.19,
       5.31, 1.46, 5.37, 6.54, 3.63, 3.13, 5.02, 0.72, 4.83, 1.5 , 0.42,
       0.16, 1.24, 5.32, 3.89, 4.12, 8.31, 2.93, 5.49, 6.18, 8.39, 8.1 ,
       5.08, 7.61, 0.18, 6.61, 2.08, 2.36, 0.55, 4.61, 7.45, 3.22, 3.86,
       8.09, 2.02, 4.64, 5.26, 5.16, 4.53, 4.44, 2.44, 0.52, 5.82, 1.25,
       1.93, 3.94, 5.15, 1.05, 3.87, 4.21, 4.46, 8.  , 6.73, 3.38, 4.65,
       8.07, 0.69, 1.59, 2.85, 7.53, 1.52, 6.05, 1.92, 4.04, 8.42, 1.  ,
       6.51, 8.08, 7.28, 1.38, 5.91, 8.21, 7.26, 1.95, 7.2 , 7.94, 7.04,
       1.76, 1.29, 1.47, 7.71, 0.84, 5.8 , 2.66, 8.01, 3.34, 7.62, 2.22,
       8.02, 6.41, 7.9 , 4.17, 0.33, 7.76, 2.75, 5.84, 7.01, 3.24, 3.12,
       7.73, 0.82, 6.96, 8.13, 3.19, 8.04, 7.46, 3.92, 1.31, 7.98, 5.52,
       5.2 , 1.34, 2.76, 0.15, 3.06, 3.97, 8.19, 3.8 , 8.2 , 7.39, 4.82,
       0.43, 4.09, 7.68, 0.74, 0.44, 1.72, 7.5 , 8.22, 0.86, 2.04, 8.28,
       5.36, 6.72, 2.6 , 3.72, 6.08, 4.92, 2.72, 8.33, 3.56, 8.17, 7.29,
       3.59, 0.77, 6.67, 2.06, 4.45, 1.71, 4.66, 2.43, 7.69, 5.77, 8.34,
       5.86, 6.38, 7.27, 6.01, 5.53, 0.87, 7.32, 1.08, 5.93, 2.48, 5.44,
       8.66, 7.03, 3.46, 5.13, 5.62, 6.88, 4.67, 6.94, 8.06, 0.61, 5.55,
       8.32, 2.23, 8.43, 2.61, 3.68, 0.36, 8.12, 1.06, 4.48, 2.33, 8.52,
       5.63, 0.03, 1.2 , 8.03, 7.6 , 3.73, 8.47, 5.96, 4.72, 4.19, 6.74,
       2.18, 0.62, 5.97, 2.39, 5.74, 4.28, 8.37, 7.11, 2.68, 7.77, 6.87,
       2.65, 4.88, 6.46, 8.26, 5.05, 0.91, 1.61, 3.6 , 0.31, 1.17, 1.14,
       8.54, 3.77, 5.03, 0.56, 7.13, 8.11, 8.15, 8.24, 8.23, 2.82, 8.05,
       0.47, 8.68, 8.5 , 6.91, 0.02, 0.04, 0.58, 0.28, 0.27])

In [13]:
waterQuality1["chromium"].unique()

array([0.83, 0.68, 0.53, 0.03, 0.69, 0.43, 0.62, 0.1 , 0.77, 0.49, 0.15,
       0.76, 0.42, 0.51, 0.54, 0.47, 0.88, 0.41, 0.2 , 0.65, 0.12, 0.61,
       0.13, 0.73, 0.25, 0.72, 0.78, 0.52, 0.17, 0.74, 0.32, 0.87, 0.26,
       0.9 , 0.36, 0.84, 0.11, 0.85, 0.09, 0.35, 0.82, 0.04, 0.81, 0.64,
       0.23, 0.45, 0.02, 0.89, 0.71, 0.6 , 0.29, 0.01, 0.31, 0.22, 0.18,
       0.33, 0.38, 0.79, 0.19, 0.46, 0.7 , 0.3 , 0.24, 0.16, 0.63, 0.39,
       0.34, 0.08, 0.8 , 0.4 , 0.14, 0.27, 0.  , 0.59, 0.28, 0.07, 0.37,
       0.21, 0.86, 0.05, 0.66, 0.55, 0.67, 0.06, 0.56, 0.58, 0.57, 0.48,
       0.5 , 0.75, 0.44])

In [14]:
waterQuality1["copper"].unique()

array([0.17, 0.66, 0.02, 1.66, 0.57, 1.38, 1.88, 1.86, 1.45, 0.82, 0.6 ,
       1.  , 1.35, 0.79, 1.54, 1.08, 1.15, 0.71, 1.82, 1.18, 1.51, 1.77,
       1.23, 1.34, 1.05, 1.09, 0.27, 1.57, 0.46, 1.53, 1.03, 1.56, 0.9 ,
       1.85, 0.91, 0.08, 0.22, 0.29, 1.92, 1.29, 1.14, 1.71, 1.59, 0.3 ,
       0.54, 1.79, 0.44, 1.97, 1.98, 0.65, 1.06, 0.14, 1.26, 1.69, 1.75,
       1.61, 0.19, 0.38, 0.34, 0.93, 0.7 , 1.55, 1.11, 0.42, 0.18, 1.28,
       1.99, 1.21, 1.3 , 0.95, 0.01, 1.44, 0.52, 1.01, 1.64, 0.76, 1.5 ,
       0.25, 0.87, 0.73, 1.1 , 0.77, 0.62, 0.36, 1.43, 1.65, 0.05, 0.16,
       0.13, 1.72, 1.67, 1.89, 0.94, 0.85, 1.7 , 0.72, 1.52, 0.24, 1.16,
       1.94, 1.95, 1.4 , 0.55, 1.39, 0.37, 0.35, 0.5 , 1.24, 1.04, 0.33,
       0.81, 1.22, 0.78, 0.04, 1.8 , 1.83, 1.37, 0.75, 0.07, 1.96, 1.07,
       0.06, 0.21, 1.33, 0.89, 0.88, 1.32, 0.98, 0.53, 1.36, 0.03, 1.74,
       1.41, 1.6 , 1.17, 0.59, 0.11, 1.46, 1.84, 0.68, 0.32, 0.8 , 1.76,
       0.67, 1.68, 0.28, 0.56, 1.49, 1.25, 0.39, 1.58, 0.4 , 0.31, 0.84,
       0.15, 0.51, 0.92, 0.86, 1.02, 1.47, 1.81, 0.69, 0.41, 1.63, 0.1 ,
       0.43, 0.09, 1.13, 0.74, 1.9 , 1.78, 1.91, 1.93, 0.26, 1.42, 0.99,
       0.63, 0.49, 1.48, 0.47, 0.48, 0.58, 1.73, 0.96, 1.19, 1.27, 0.2 ,
       0.61, 0.12, 2.  , 1.87, 0.83, 1.2 , 0.97, 0.45, 0.64, 0.23, 1.62,
       1.31, 1.12, 0.  ])

In [15]:
waterQuality1["flouride"].unique()

array([0.05, 0.9 , 0.99, 1.08, 0.61, 0.11, 0.33, 0.86, 0.98, 1.24, 1.29,
       0.58, 0.09, 1.07, 0.54, 0.62, 1.43, 0.34, 0.22, 1.  , 1.46, 0.43,
       1.44, 0.29, 1.35, 0.53, 0.26, 1.41, 0.87, 0.51, 0.91, 0.  , 0.55,
       0.42, 0.4 , 0.68, 1.2 , 1.04, 0.36, 1.42, 0.52, 0.14, 0.89, 1.33,
       0.59, 0.66, 0.75, 0.1 , 0.15, 1.01, 0.83, 0.03, 1.47, 1.28, 0.45,
       0.02, 0.2 , 0.32, 1.09, 1.13, 0.13, 1.14, 1.21, 0.5 , 0.28, 0.3 ,
       0.01, 1.16, 0.69, 1.25, 1.48, 0.76, 0.97, 0.73, 1.49, 0.08, 1.18,
       0.25, 1.06, 0.16, 0.04, 1.27, 1.38, 1.12, 0.74, 0.93, 0.92, 1.39,
       0.07, 0.24, 0.48, 0.37, 0.85, 1.4 , 1.03, 0.65, 0.44, 0.7 , 0.79,
       0.82, 1.5 , 1.19, 0.78, 1.34, 0.96, 0.8 , 0.19, 1.45, 1.23, 1.37,
       0.49, 0.23, 1.26, 0.95, 0.88, 1.32, 0.17, 0.84, 1.3 , 0.64, 0.21,
       0.81, 0.12, 0.94, 1.05, 1.11, 0.63, 0.57, 1.31, 0.67, 0.77, 0.46,
       0.06, 0.38, 1.22, 0.72, 1.36, 0.31, 1.02, 0.27, 0.47, 1.1 , 0.41,
       1.15, 0.71, 0.18, 0.56, 0.6 , 0.35, 1.17, 0.39])

In [16]:
waterQuality1["bacteria"].unique()

array([0.2 , 0.65, 0.05, 0.71, 0.13, 0.67, 0.16, 0.35, 0.83, 0.04, 0.52,
       0.91, 0.7 , 0.23, 0.89, 0.85, 0.75, 0.99, 0.92, 0.58, 0.8 , 0.56,
       0.96, 0.25, 0.44, 0.69, 0.08, 0.77, 0.38, 0.12, 0.3 , 0.26, 0.63,
       0.86, 0.32, 0.49, 0.27, 0.18, 0.06, 0.79, 0.84, 0.42, 0.98, 0.24,
       0.74, 0.76, 0.51, 0.72, 0.07, 0.53, 0.45, 0.39, 0.1 , 0.31, 0.11,
       0.64, 0.57, 0.82, 0.87, 0.55, 0.14, 1.  , 0.47, 0.33, 0.09, 0.28,
       0.19, 0.78, 0.02, 0.41, 0.46, 0.61, 0.62, 0.5 , 0.59, 0.15, 0.48,
       0.68, 0.01, 0.73, 0.22, 0.21, 0.34, 0.43, 0.93, 0.66, 0.36, 0.17,
       0.6 , 0.37, 0.29, 0.97, 0.95, 0.9 , 0.03, 0.4 , 0.94, 0.54, 0.81,
       0.88, 0.  ])

In [17]:
waterQuality1["viruses"].unique()

array([0.   , 0.65 , 0.003, 0.71 , 0.001, 0.67 , 0.007, 0.005, 0.002,
       0.83 , 0.008, 0.52 , 0.91 , 0.7  , 0.009, 0.89 , 0.85 , 0.75 ,
       0.99 , 0.92 , 0.58 , 0.8  , 0.56 , 0.96 , 0.69 , 0.006, 0.77 ,
       0.004, 0.63 , 0.86 , 0.79 , 0.84 , 0.98 , 0.74 , 0.76 , 0.51 ,
       0.72 , 0.53 , 0.64 , 0.57 , 0.82 , 0.87 , 0.55 , 1.   , 0.78 ,
       0.61 , 0.62 , 0.5  , 0.59 , 0.68 , 0.73 , 0.93 , 0.66 , 0.6  ,
       0.97 , 0.95 , 0.9  , 0.94 , 0.54 , 0.81 , 0.88 ])

In [18]:
waterQuality1["lead"].unique()

array([0.054, 0.1  , 0.078, 0.016, 0.117, 0.135, 0.021, 0.197, 0.167,
       0.109, 0.145, 0.011, 0.103, 0.101, 0.126, 0.017, 0.08 , 0.065,
       0.071, 0.108, 0.086, 0.061, 0.114, 0.012, 0.031, 0.11 , 0.182,
       0.049, 0.079, 0.013, 0.193, 0.091, 0.124, 0.107, 0.085, 0.146,
       0.162, 0.048, 0.082, 0.141, 0.131, 0.069, 0.136, 0.166, 0.112,
       0.169, 0.093, 0.025, 0.139, 0.184, 0.015, 0.09 , 0.068, 0.123,
       0.177, 0.149, 0.062, 0.121, 0.105, 0.168, 0.137, 0.189, 0.095,
       0.053, 0.113, 0.132, 0.175, 0.045, 0.036, 0.033, 0.191, 0.127,
       0.032, 0.052, 0.047, 0.019, 0.129, 0.153, 0.147, 0.12 , 0.003,
       0.16 , 0.18 , 0.072, 0.042, 0.092, 0.023, 0.185, 0.07 , 0.083,
       0.155, 0.164, 0.17 , 0.043, 0.198, 0.194, 0.089, 0.044, 0.087,
       0.122, 0.088, 0.158, 0.074, 0.148, 0.172, 0.041, 0.176, 0.038,
       0.005, 0.181, 0.159, 0.05 , 0.156, 0.034, 0.138, 0.102, 0.064,
       0.157, 0.008, 0.059, 0.037, 0.118, 0.116, 0.06 , 0.075, 0.04 ,
       0.024, 0.144, 0.152, 0.119, 0.125, 0.067, 0.192, 0.051, 0.187,
       0.007, 0.01 , 0.13 , 0.096, 0.15 , 0.014, 0.171, 0.03 , 0.199,
       0.076, 0.097, 0.174, 0.106, 0.188, 0.099, 0.154, 0.027, 0.115,
       0.026, 0.163, 0.196, 0.057, 0.035, 0.02 , 0.178, 0.018, 0.142,
       0.14 , 0.134, 0.028, 0.183, 0.19 , 0.006, 0.073, 0.143, 0.173,
       0.128, 0.2  , 0.179, 0.004, 0.186, 0.111, 0.039, 0.104, 0.056,
       0.133, 0.165, 0.022, 0.063, 0.098, 0.066, 0.195, 0.002, 0.081,
       0.151, 0.094, 0.046, 0.009, 0.077, 0.161, 0.084, 0.055, 0.058,
       0.001, 0.   ])

In [19]:
waterQuality1["nitrates"].unique()

array([16.08,  2.01, 14.16, ..., 12.76, 19.8 ,  0.  ])

In [20]:
waterQuality1["nitrites"].unique()

array([1.13, 1.93, 1.11, 1.29, 1.89, 1.78, 1.81, 1.84, 1.46, 1.25, 1.49,
       1.95, 1.82, 1.08, 1.2 , 1.53, 1.22, 1.76, 1.41, 1.5 , 1.18, 1.74,
       1.92, 1.07, 1.7 , 1.69, 1.43, 1.19, 1.55, 1.  , 1.27, 1.86, 1.35,
       1.56, 1.83, 1.68, 1.73, 1.09, 1.28, 1.34, 1.21, 1.87, 1.45, 1.24,
       1.79, 1.37, 1.48, 1.16, 1.4 , 1.57, 1.88, 1.59, 1.36, 1.9 , 1.06,
       1.04, 1.58, 1.31, 1.38, 1.17, 1.3 , 1.02, 1.65, 1.47, 1.14, 1.51,
       1.66, 1.99, 1.26, 1.91, 1.42, 1.33, 1.97, 1.03, 1.8 , 1.1 , 1.05,
       1.64, 1.44, 1.15, 1.63, 1.72, 1.23, 1.85, 1.67, 1.6 , 1.54, 1.94,
       1.12, 1.62, 1.52, 1.32, 1.98, 1.77, 1.61, 1.01, 1.75, 1.71, 2.  ,
       1.96, 1.39, 2.12, 2.43, 2.03, 2.08, 2.06, 2.09, 2.19, 2.01, 2.27,
       2.38, 2.02, 2.36, 2.44, 2.22, 2.21, 2.72, 2.25, 2.24, 2.28, 2.07,
       2.2 , 2.62, 2.18, 2.04, 2.49, 2.29, 2.68, 2.56, 2.23, 2.58, 2.17,
       2.05, 2.16, 2.53, 2.3 , 2.35, 2.11, 2.75, 2.26, 2.89, 2.52, 2.86,
       2.34, 2.1 , 2.63, 2.37, 2.33, 2.14, 2.42, 2.15, 2.41, 2.64, 2.61,
       2.73, 2.48, 2.54, 2.83, 2.39, 2.55, 2.47, 2.8 , 2.6 , 2.32, 2.5 ,
       2.57, 2.69, 2.13, 2.46, 2.59, 2.31, 2.65, 2.92, 2.71, 2.74, 2.45,
       0.93, 0.54, 0.77, 0.1 , 0.67, 0.46, 0.21, 0.89, 0.03, 0.18, 0.48,
       0.8 , 0.85, 0.68, 0.4 , 0.73, 0.32, 0.15, 0.04, 0.33, 0.42, 0.81,
       0.02, 0.26, 0.72, 0.34, 0.6 , 0.63, 0.91, 0.95, 0.11, 0.16, 0.47,
       0.44, 0.19, 0.12, 0.39, 0.83, 0.25, 0.82, 0.09, 0.96, 0.22, 0.71,
       0.74, 0.05, 0.87, 0.57, 0.58, 0.76, 0.97, 0.17, 0.92, 0.7 , 0.84,
       0.86, 0.27, 0.51, 0.55, 0.31, 0.64, 0.23, 0.41, 0.2 , 0.49, 0.08,
       0.62, 0.45, 0.37, 0.43, 0.13, 0.28, 0.38, 0.36, 0.29, 0.98, 0.9 ,
       0.07, 0.61, 0.06, 0.66, 0.53, 0.88, 0.56, 0.79, 0.99, 0.14, 0.69,
       0.  , 0.94, 0.78, 0.3 , 0.59, 0.24, 0.75, 0.01, 0.52, 0.35, 0.5 ,
       0.65, 2.66, 2.51, 2.93, 2.4 ])

In [21]:
waterQuality1["mercury"].unique()

array([0.007, 0.003, 0.006, 0.004, 0.001, 0.01 , 0.009, 0.008, 0.002,
       0.005, 0.   ])

In [22]:
waterQuality1["perchlorate"].unique()

array([37.75, 32.26, 50.28, ..., 12.74,  9.42,  8.44])

In [23]:
waterQuality1["radium"].unique()

array([6.78, 3.21, 7.07, 1.72, 2.41, 5.42, 2.84, 7.24, 4.99, 0.08, 7.8 ,
       1.3 , 1.97, 5.58, 4.33, 0.98, 6.89, 1.14, 1.  , 0.88, 3.05, 1.74,
       0.9 , 3.22, 7.99, 0.49, 1.15, 3.29, 2.39, 4.55, 7.77, 2.21, 6.16,
       1.71, 3.76, 6.15, 3.19, 0.5 , 4.7 , 6.14, 5.45, 0.37, 3.39, 2.18,
       2.3 , 2.67, 4.27, 2.91, 4.12, 0.92, 1.53, 7.12, 5.63, 5.8 , 7.18,
       4.87, 4.86, 4.34, 2.75, 3.81, 6.13, 4.91, 4.39, 6.65, 3.75, 0.63,
       1.44, 7.4 , 7.81, 2.95, 1.29, 2.73, 6.35, 6.53, 7.02, 2.92, 2.35,
       6.11, 0.86, 0.28, 5.14, 5.41, 4.15, 2.24, 6.46, 4.74, 1.08, 4.29,
       6.98, 3.95, 3.32, 1.62, 7.6 , 6.6 , 1.2 , 6.36, 4.96, 5.77, 4.48,
       6.74, 4.41, 6.28, 7.28, 1.45, 5.26, 2.2 , 0.25, 3.4 , 4.23, 4.14,
       3.09, 2.58, 3.49, 1.39, 3.04, 0.68, 7.9 , 5.99, 4.8 , 5.11, 2.4 ,
       2.53, 2.9 , 6.59, 3.42, 4.16, 1.23, 5.9 , 7.25, 6.42, 3.44, 1.67,
       2.65, 6.2 , 6.66, 4.35, 3.24, 7.35, 3.23, 4.63, 6.49, 1.31, 3.72,
       6.75, 6.63, 4.47, 7.42, 7.85, 4.05, 0.77, 2.68, 1.55, 6.7 , 3.07,
       1.27, 2.01, 6.25, 1.18, 1.04, 1.51, 7.67, 3.36, 7.08, 6.83, 5.56,
       7.94, 6.5 , 5.78, 0.51, 2.87, 4.95, 1.83, 4.85, 3.73, 6.9 , 0.53,
       3.52, 3.57, 7.46, 2.96, 4.17, 7.29, 0.4 , 2.48, 4.72, 6.79, 6.19,
       5.19, 7.62, 5.48, 1.89, 0.45, 3.65, 7.03, 5.96, 2.66, 6.56, 7.27,
       4.38, 2.38, 0.34, 5.92, 6.88, 7.92, 3.48, 7.21, 6.84, 1.5 , 2.12,
       0.66, 5.85, 7.15, 1.22, 0.99, 4.4 , 5.87, 6.81, 2.36, 1.1 , 1.38,
       2.6 , 4.25, 5.43, 6.47, 3.12, 2.14, 6.93, 6.07, 0.3 , 5.82, 5.33,
       5.15, 7.74, 4.78, 0.89, 2.52, 0.59, 2.78, 6.33, 1.07, 2.44, 3.14,
       5.66, 7.22, 5.24, 5.93, 0.6 , 3.74, 5.64, 7.73, 7.19, 1.78, 5.22,
       1.63, 3.51, 0.91, 4.53, 0.06, 0.18, 4.62, 2.19, 5.84, 5.69, 3.92,
       0.41, 5.73, 6.32, 1.95, 3.66, 5.83, 4.51, 4.54, 1.75, 2.82, 2.97,
       4.01, 7.79, 3.87, 3.01, 2.  , 0.05, 7.37, 6.62, 1.16, 6.29, 0.  ,
       4.28, 7.04, 6.52, 0.87, 0.94, 0.97, 6.82, 2.86, 0.72, 0.54, 4.82,
       0.01, 6.69, 2.54, 3.63, 4.73, 3.41, 7.71, 5.59, 3.1 , 5.86, 1.9 ,
       7.43, 4.61, 3.69, 2.13, 3.11, 2.74, 4.45, 4.58, 3.46, 4.89, 1.94,
       1.01, 5.55, 5.21, 3.61, 1.8 , 4.76, 0.85, 1.69, 0.74, 5.65, 4.18,
       5.88, 1.92, 0.93, 1.86, 0.55, 6.38, 7.36, 3.71, 0.09, 0.43, 3.5 ,
       2.83, 4.3 , 4.49, 2.99, 0.67, 4.32, 0.23, 6.21, 3.18, 7.88, 3.03,
       3.97, 1.11, 5.31, 5.52, 5.35, 2.06, 1.46, 1.91, 7.32, 1.25, 1.56,
       5.38, 1.36, 3.83, 3.58, 0.16, 4.06, 1.12, 2.56, 5.76, 6.23, 7.53,
       4.88, 1.32, 4.5 , 3.28, 1.54, 3.6 , 7.52, 4.31, 2.27, 7.11, 4.04,
       6.87, 7.56, 5.57, 5.03, 6.3 , 2.28, 0.75, 5.81, 7.1 , 6.08, 2.59,
       3.54, 0.8 , 7.82, 4.66, 4.98, 0.15, 6.72, 7.48, 6.31, 1.79, 0.1 ,
       0.73, 0.95, 5.49, 5.61, 2.77, 7.68, 2.61, 1.02, 2.08, 7.47, 4.1 ,
       1.34, 1.03, 7.23, 5.13, 0.38, 2.62, 7.05, 3.62, 2.07, 2.71, 2.88,
       6.44, 5.75, 4.77, 6.05, 2.37, 0.14, 2.22, 7.51, 3.8 , 1.06, 6.85,
       4.26, 4.94, 4.13, 0.78, 7.87, 6.09, 7.01, 7.78, 5.62, 2.55, 2.57,
       4.21, 5.12, 3.55, 7.31, 4.08, 3.64, 6.58, 1.68, 6.06, 1.6 , 4.2 ,
       7.69, 0.83, 2.63, 4.02, 5.37, 3.93, 7.5 , 5.17, 5.54, 2.26, 4.64,
       4.67, 0.82, 7.55, 2.89, 4.69, 5.34, 5.18, 7.54, 1.7 , 3.43, 0.96,
       7.64, 6.96, 2.15, 5.67, 1.84, 3.91, 4.37, 1.66, 7.76, 0.7 , 4.52,
       2.42, 3.86, 5.1 , 6.43, 1.65, 0.35, 5.06, 0.64, 5.94, 7.38, 6.68,
       5.16, 6.  , 7.16, 4.07, 5.01, 0.02, 7.3 , 1.64, 3.02, 1.05, 6.26,
       4.  , 5.95, 1.82, 7.63, 6.67, 0.62, 7.59, 4.83, 4.9 , 3.9 , 7.2 ,
       3.17, 6.8 , 0.46, 1.76, 0.27, 2.76, 2.31, 4.71, 3.59, 7.7 , 3.34,
       5.29, 4.59, 5.97, 3.08, 6.24, 0.19, 3.  , 5.32, 7.65, 7.17, 6.02,
       6.17, 1.42, 7.93, 3.13, 4.6 , 0.79, 6.12, 3.56, 1.4 , 3.37, 0.22,
       7.97, 4.03, 2.69, 0.56, 6.71, 2.94, 1.35, 6.55, 2.17, 0.32, 1.77,
       5.7 , 5.6 , 1.98, 1.57, 0.24, 0.2 , 4.79, 3.78, 0.84, 1.73, 2.16,
       4.84, 2.8 , 3.2 , 4.36, 0.07, 1.96, 2.46, 0.47, 0.58, 0.76, 0.61,
       0.17, 1.81, 0.31, 0.81, 0.36, 3.25, 1.41, 2.72, 0.21, 0.42, 0.39,
       2.49, 1.99, 2.23, 0.04, 2.5 , 0.29, 3.3 , 1.37, 4.42, 1.61, 5.  ,
       0.12, 0.03, 2.34, 0.33, 0.13, 3.31, 6.94, 0.26, 2.04, 0.52, 2.79,
       1.48, 1.19, 3.06, 1.49, 3.84, 1.93, 2.64, 1.28, 0.65, 1.13, 2.25,
       1.58, 0.57, 0.48, 0.69, 0.11, 2.93, 0.71, 3.33, 0.44, 3.53, 5.51,
       1.47, 3.94, 1.87, 6.61, 5.39, 2.43, 1.88, 1.43, 3.35, 1.17, 5.25,
       1.59, 2.47, 4.56, 6.41, 2.03, 3.26, 2.51, 3.47, 2.02, 1.26, 2.32,
       4.81, 3.16, 2.11, 3.96, 1.24, 3.68, 2.33, 5.05, 3.27, 5.2 , 1.52,
       3.85, 3.77, 2.05, 1.21, 2.45, 3.79, 2.98, 4.19, 3.98, 5.02, 1.33,
       3.88, 4.44, 3.67, 5.44, 1.85, 3.7 , 6.34, 1.09, 5.74, 2.7 , 4.46,
       3.82, 2.09, 6.73, 6.4 , 4.24, 3.38, 5.71, 4.57, 3.89, 5.53, 5.28,
       4.75, 5.4 , 6.01, 4.93, 6.86, 5.36, 2.85, 3.15, 3.99, 4.68, 6.45,
       5.07, 5.23, 5.3 , 4.09, 2.81, 4.22, 6.64, 6.97, 6.22])

In [24]:
waterQuality1["selenium"].unique()

array([0.08, 0.07, 0.02, 0.1 , 0.03, 0.05, 0.09, 0.01, 0.06, 0.  , 0.04])

In [25]:
waterQuality1["silver"].unique()

array([0.34, 0.27, 0.44, 0.45, 0.06, 0.19, 0.24, 0.08, 0.25, 0.31, 0.33,
       0.48, 0.38, 0.05, 0.47, 0.12, 0.4 , 0.41, 0.1 , 0.13, 0.01, 0.16,
       0.18, 0.5 , 0.26, 0.17, 0.2 , 0.11, 0.3 , 0.37, 0.35, 0.04, 0.46,
       0.  , 0.43, 0.42, 0.03, 0.28, 0.02, 0.21, 0.32, 0.09, 0.15, 0.14,
       0.29, 0.22, 0.39, 0.36, 0.23, 0.07, 0.49])

In [26]:
waterQuality1["uranium"].unique()

array([0.02, 0.05, 0.01, 0.08, 0.07, 0.06, 0.03, 0.  , 0.04, 0.09])

In [27]:
waterQuality1["is_safe"].unique()

array(['1', '0', '#NUM!'], dtype=object)

4. Выводим все уникальные значения в каждой из колонок в датасете.

In [29]:
waterQuality1.sort_values(by='uranium')

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
2118,0.13,16.35,0.030,2.90,0.008,5.14,0.29,1.50,0.25,0.02,...,0.083,6.22,1.91,0.009,50.04,1.39,0.02,0.11,0.00,0
5740,0.06,5.22,0.040,0.20,0.030,0.08,0.03,0.03,0.15,0.09,...,0.165,17.06,0.56,0.003,0.15,0.18,0.01,0.01,0.00,0
5736,0.10,24.24,0.080,0.40,0.020,0.17,0.01,1.65,0.69,0.74,...,0.046,12.31,0.53,0.003,0.48,0.92,0.01,0.06,0.00,0
2878,0.03,24.89,0.001,2.40,0.005,4.90,0.59,1.07,1.04,0.76,...,0.043,2.65,1.87,0.002,35.64,3.13,0.08,0.27,0.00,0
1842,0.55,8.06,0.960,2.72,0.040,0.66,0.88,0.69,1.32,0.62,...,0.103,13.87,1.57,0.010,15.66,5.29,0.06,0.46,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4493,0.06,23.89,0.050,0.32,0.060,0.33,0.09,0.08,0.21,0.00,...,0.092,5.21,0.78,0.010,5.86,3.07,0.08,0.00,0.09,0
4492,0.03,13.15,0.020,1.42,0.080,0.01,0.02,0.01,0.10,0.00,...,0.165,10.82,0.53,0.006,0.17,0.72,0.07,0.08,0.09,0
1272,3.78,4.59,0.370,0.47,0.040,1.99,0.69,1.49,0.75,0.00,...,0.099,10.50,1.85,0.007,11.27,6.53,0.02,0.07,0.09,0
7350,0.09,26.46,0.020,0.91,0.090,0.53,0.05,1.02,1.24,0.44,...,0.197,11.14,1.55,0.002,1.70,2.62,0.08,0.02,0.09,0
2120,0.29,5.43,0.040,2.34,0.002,4.13,0.70,1.51,0.89,0.55,...,0.164,8.49,1.49,0.001,37.15,0.25,0.08,0.01,0.09,0

5. Отсортировка по параметру уран - "uranium", в котором произошла отсортировака по возрастаню от минимального значения - 0.0 до максимального значения - 0.09 .

In [32]:

waterQuality1.sort_values(by='silver', ascending=False)

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
2903,0.09,8.11,0.01,1.47,0.007,3.27,0.77,1.56,1.47,0.97,...,0.166,12.39,1.29,0.005,47.39,3.54,0.05,0.5,0.01,0
693,4.59,3.44,0.01,2.55,0.009,5.17,0.37,1.20,1.45,0.00,...,0.091,13.66,1.66,0.001,31.78,2.07,0.04,0.5,0.09,1
2122,0.15,29.72,0.02,1.40,0.008,3.71,0.47,1.16,1.06,0.82,...,0.120,6.63,1.57,0.001,4.28,7.90,0.04,0.5,0.04,0
3122,0.02,29.62,0.34,2.10,0.040,3.81,0.47,1.16,1.06,0.82,...,0.120,6.98,2.22,0.001,46.16,7.90,0.04,0.5,0.04,0
3564,0.08,0.41,0.57,2.66,0.080,1.17,0.33,0.06,1.49,0.15,...,0.001,10.11,1.85,0.007,53.45,2.54,0.04,0.5,0.09,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6731,0.02,10.42,0.04,2.48,0.090,0.20,0.00,0.07,0.73,0.06,...,0.157,10.83,1.84,0.006,3.33,0.10,0.03,0.0,0.04,0
4987,0.00,26,0.08,0.31,0.040,0.02,0.05,1.62,0.96,0.00,...,0.138,5.66,0.34,0.000,0.44,0.52,0.01,0.0,0.06,0
6737,0.01,18.88,0.02,0.99,0.060,0.00,0.04,1.26,1.04,0.17,...,0.200,16.09,1.23,0.005,0.09,2.62,0.06,0.0,0.05,0
2370,0.06,19.59,0.04,0.79,0.007,6.30,0.31,1.91,0.96,0.14,...,0.132,16.05,1.09,0.010,49.72,5.19,0.02,0.0,0.02,0
3999,0.05,8.83,0.00,0.97,0.080,0.09,0.01,0.03,0.05,0.00,...,0.054,16.08,0.93,0.007,3.57,0.28,0.08,0.0,0.02,0

5. Отсортировка по параметру серебро - "silver", в котором произошла отсортировака по убыванию от максимального значения - 0.5 до минимального значения - 0.0

In [34]:
waterQuality1.drop(columns = ["nitrites"])

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,viruses,lead,nitrates,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,0.000,0.054,16.08,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,0.650,0.100,2.01,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,0.003,0.078,14.16,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,0.710,0.016,1.41,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,0.001,0.117,6.74,0.003,16.90,2.41,0.02,0.06,0.02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,0.05,7.78,0.00,1.95,0.040,0.10,0.03,0.03,1.37,0.00,0.000,0.197,14.29,0.005,3.57,2.13,0.09,0.06,0.03,1
7995,0.05,24.22,0.02,0.59,0.010,0.45,0.02,0.02,1.48,0.00,0.000,0.031,10.27,0.001,1.48,1.11,0.09,0.10,0.08,1
7996,0.09,6.85,0.00,0.61,0.030,0.05,0.05,0.02,0.91,0.00,0.000,0.182,15.92,0.000,1.35,4.84,0.00,0.04,0.05,1
7997,0.01,10,0.01,2.00,0.000,2.00,0.00,0.09,0.00,0.00,0.000,0.000,0.00,0.000,0.00,0.00,0.00,0.00,0.00,1
7998,0.04,6.85,0.01,0.70,0.030,0.05,0.01,0.03,1.00,0.00,0.000,0.182,15.92,0.000,1.35,4.84,0.00,0.04,0.05,1

6. Удаление колонки с именем "nitrites".

In [38]:
waterQuality1.drop([1,2], axis=0, inplace=True)
waterQuality1

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1
5,0.94,14.47,0.03,2.88,0.003,0.80,0.43,1.38,0.11,0.67,...,0.135,9.75,1.89,0.006,27.17,5.42,0.08,0.19,0.02,1
6,2.36,5.6,0.01,1.35,0.004,1.28,0.62,1.88,0.33,0.13,...,0.021,18.60,1.78,0.007,45.34,2.84,0.10,0.24,0.08,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,0.05,7.78,0.00,1.95,0.040,0.10,0.03,0.03,1.37,0.00,...,0.197,14.29,1.00,0.005,3.57,2.13,0.09,0.06,0.03,1
7995,0.05,24.22,0.02,0.59,0.010,0.45,0.02,0.02,1.48,0.00,...,0.031,10.27,1.00,0.001,1.48,1.11,0.09,0.10,0.08,1
7996,0.09,6.85,0.00,0.61,0.030,0.05,0.05,0.02,0.91,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1
7997,0.01,10,0.01,2.00,0.000,2.00,0.00,0.09,0.00,0.00,...,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,1
7998,0.04,6.85,0.01,0.70,0.030,0.05,0.01,0.03,1.00,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1

6. Удаление строк с индексами 1 и 2 во всм датасете.

In [62]:
waterQuality1=waterQuality1.replace({"perchlorate":9.12},10)
waterQuality1

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,10.00,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1
5,0.94,14.47,0.03,2.88,0.003,0.80,0.43,1.38,0.11,0.67,...,0.135,9.75,1.89,0.006,27.17,5.42,0.08,0.19,0.02,1
6,2.36,5.6,0.01,1.35,0.004,1.28,0.62,1.88,0.33,0.13,...,0.021,18.60,1.78,0.007,45.34,2.84,0.10,0.24,0.08,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,0.05,7.78,0.00,1.95,0.040,0.10,0.03,0.03,1.37,0.00,...,0.197,14.29,1.00,0.005,3.57,2.13,0.09,0.06,0.03,1
7995,0.05,24.22,0.02,0.59,0.010,0.45,0.02,0.02,1.48,0.00,...,0.031,10.27,1.00,0.001,1.48,1.11,0.09,0.10,0.08,1
7996,0.09,6.85,0.00,0.61,0.030,0.05,0.05,0.02,0.91,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1
7997,0.01,10,0.01,2.00,0.000,2.00,0.00,0.09,0.00,0.00,...,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,1
7998,0.04,6.85,0.01,0.70,0.030,0.05,0.01,0.03,1.00,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1

7.Заменена всех значений 9.12 в колонке perchlorate на значение 10.

In [53]:
waterQuality1.drop_duplicates()

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1
5,0.94,14.47,0.03,2.88,0.003,0.80,0.43,1.38,0.11,0.67,...,0.135,9.75,1.89,0.006,27.17,5.42,0.08,0.19,0.02,1
6,2.36,5.6,0.01,1.35,0.004,1.28,0.62,1.88,0.33,0.13,...,0.021,18.60,1.78,0.007,45.34,2.84,0.10,0.24,0.08,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,0.05,7.78,0.00,1.95,0.040,0.10,0.03,0.03,1.37,0.00,...,0.197,14.29,1.00,0.005,3.57,2.13,0.09,0.06,0.03,1
7995,0.05,24.22,0.02,0.59,0.010,0.45,0.02,0.02,1.48,0.00,...,0.031,10.27,1.00,0.001,1.48,1.11,0.09,0.10,0.08,1
7996,0.09,6.85,0.00,0.61,0.030,0.05,0.05,0.02,0.91,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1
7997,0.01,10,0.01,2.00,0.000,2.00,0.00,0.09,0.00,0.00,...,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,1
7998,0.04,6.85,0.01,0.70,0.030,0.05,0.01,0.03,1.00,0.00,...,0.182,15.92,1.00,0.000,1.35,4.84,0.00,0.04,0.05,1

8. Удаление дубликатов во всем датасете, которое позволяет нам читабельность таблицы сделать лучше.

In [54]:
waterQuality1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7997 entries, 0 to 7998
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   aluminium    7997 non-null   float64
 1   ammonia      7997 non-null   object
 2   arsenic      7997 non-null   float64
 3   barium       7997 non-null   float64
 4   cadmium      7997 non-null   float64
 5   chloramine   7997 non-null   float64
 6   chromium     7997 non-null   float64
 7   copper       7997 non-null   float64
 8   flouride     7997 non-null   float64
 9   bacteria     7997 non-null   float64
 10  viruses      7997 non-null   float64
 11  lead         7997 non-null   float64
 12  nitrates     7997 non-null   float64
 13  nitrites     7997 non-null   float64
 14  mercury      7997 non-null   float64
 15  perchlorate  7997 non-null   float64
 16  radium       7997 non-null   float64
 17  selenium     7997 non-null   float64
 18  silver       7997 non-null   float64
 19  uranium      7997 non-null   float64
 20  is_safe      7997 non-null   object
dtypes: float64(19), object(2)
memory usage: 1.3+ MB

9. Проведен анализ с помощью функций info, которая позволяет вывести общую информацию о дататайме, к примеру, функция вывела, что здесь находится 21 столбец, типы внесенных данных в таблицу и каково их кол-во, 7997 строк.

In [55]:
waterQuality1.describe()

,aluminium,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,viruses,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium
count,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000,7997.000000
mean,0.665908,0.161479,1.567620,0.042816,2.176185,0.247136,0.805973,0.771522,0.319657,0.328583,0.099452,9.819256,1.329914,0.005194,16.454094,2.919992,0.049679,0.147729,0.044677
std,1.265162,0.252613,1.216037,0.036049,2.567010,0.270612,0.653560,0.435418,0.329492,0.378109,0.058179,5.541124,0.573247,0.002967,17.684759,2.322833,0.028771,0.143525,0.026904
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.040000,0.030000,0.560000,0.008000,0.100000,0.050000,0.090000,0.400000,0.000000,0.002000,0.048000,5.000000,1.000000,0.003000,2.170000,0.820000,0.020000,0.040000,0.020000
50%,0.070000,0.050000,1.190000,0.040000,0.530000,0.090000,0.750000,0.770000,0.220000,0.008000,0.102000,9.930000,1.420000,0.005000,7.740000,2.410000,0.050000,0.080000,0.050000
75%,0.280000,0.100000,2.480000,0.070000,4.240000,0.440000,1.390000,1.160000,0.610000,0.700000,0.151000,14.610000,1.760000,0.008000,29.450000,4.670000,0.070000,0.240000,0.070000
max,5.050000,1.050000,4.940000,0.130000,8.680000,0.900000,2.000000,1.500000,1.000000,1.000000,0.200000,19.830000,2.930000,0.010000,60.010000,7.990000,0.100000,0.500000,0.090000

10. Проведен анализ с помощью функций describe в датасете, который вывел для каждого столбца свои статические показатели, к примеру, видно, что максимальное значение - в столбце "aluminium" = 5.050000, а а минимально значение в данном столбце = 0.000000.

In [61]:
subset = waterQuality1.loc[[0, 4, 3], ['aluminium', 'arsenic', 'barium']]
subset

   aluminium  arsenic  barium
0       1.65     0.04    2.85
4       0.92     0.03    0.20
3       1.36     0.04    2.96

11. Проведена выборка данных по строкам и столбцам с помощью loc, то есть в начале были указаны индексы строк =, которые необходимо вывести, а затем столбцы, чьи значения можно тнпнрь сравнить из новой таблицы.

In [63]:
waterQuality1.to_csv("waterQuality1_clear.csv")

12. Сохранение нового датасета

Вывод: был реализован базовый анализ датасета: был выведен весь датасет и описан, выведена размерноть массива, выведены наименования всех колонок, написано что они означают в датасете, выведены все уникальные значения,отсортированы по определенным параметрам, удалены ненужные столбцы или строчки, заменены определенные значения в датасете, удалены дубликаты, проведен анализ с помощью функций info, проведен анализ с помощью функций describe, проведена выборку данных по строкам и столбцам с помощью loc, сохранен новый датасет, сделан вывод по каждому пункту и описать все.